version: '3.8'

services:
  youtube-mp3:
    image: node:18
    container_name: youtube-mp3-api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && apt-get update && apt-get install -y ffmpeg && node server.js"
